### ISSUE TITLE
Segfault in stop() function

### ISSUE THREAD

**Issue by lenonk** [nirosys/serenity#9]
Hey man!  I hope everything is going well for you!  In the stop() function, is_running can be uninitialized, which can result in a segfault.  If you'll give me permission to push, I have it fixed locally.

If not, here's the patch ;)

diff --git a/include/serenity/net/server.hpp b/include/serenity/net/server.hpp
index 0e986bc..d82ad0c 100644
--- a/include/serenity/net/server.hpp
+++ b/include/serenity/net/server.hpp
@@ -78,7 +78,7 @@ namespace serenity { namespace net {
             std::thread running_thread_;
             std::mutex stop_mutex_;
             std::condition_variable stop_condition_;
-            bool is_running_;
+            bool is_running_ = false;
 
             manager connection_manager_;
             resolver service_resolver_;
@@ -162,7 +162,8 @@ namespace serenity { namespace net {
 
     template <class resolver_type>
     void server<resolver_type>::stop() {
-        acceptor_.close();
+        if (acceptor_.is_open())
+            acceptor_.close();
         if (is_running_) {
             std::unique_lock<std::mutex> lk(stop_mutex_);
             io_service_.stop();

**Comment by nirosys** [comment]
Hey man! Just added you as a collaborator :)

**Comment by lenonk** [comment]
Thank you sir!
